version: 0.2

phases:
  build:
    commands:
      - chmod +x build.sh
      - ./build.sh deploy dev

# more details on the build template can be found at 
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax